# Generated by Django 5.2.9 on 2025-12-05 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Titre optionnel de la discussion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenu à analyser (texte, URL, etc.)')),
                ('content_type', models.CharField(choices=[('TEXT', 'Texte'), ('IMAGE', 'Image'), ('TWEET', 'Tweet'), ('ARTICLE', 'Article')], default='TEXT', help_text='Type de contenu analysé', max_length=10)),
                ('reliability_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score de fiabilité (0-100)', max_digits=5, null=True)),
                ('explanation', models.TextField(blank=True, help_text="Explication de l'analyse par l'IA", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(help_text='Discussion à laquelle appartient cette analyse', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='store.discussion')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['user', '-updated_at'], name='store_discu_user_id_56bc74_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['discussion', '-created_at'], name='store_analy_discuss_9ba54c_idx'),
        ),
    ]
