# Generated by Django 3.2.7 on 2025-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_add_discussion_model'),
        ('store', '0015_auto_20251204_2203'),
    ]
    
    # Note: Cette migration merge deux branches de migrations
    # La migration 0017 a été supprimée car elle causait des conflits avec les FK

    operations = [
    ]
