# Generated by Django 3.2.7 on 2025-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20251204_2249'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['discussion', '-created_at'], name='store_analy_discuss_9ba54c_idx'),
        ),
    ]
