# Generated by Django 5.2.9 on 2025-12-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_analysis_store_analy_discuss_9ba54c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='explanation',
            field=models.TextField(blank=True, help_text="Explication de l'analyse par l'IA", null=True),
        ),
    ]
